services:
  kodus-orchestrator:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "3001:3001"
    environment:
      - ENV=homolog
      - API_NODE_ENV=homolog
    env_file:
      - .env.qa
    networks:
      - shared-network
    restart: unless-stopped
    secrets:
      - source: ast_root_ca
        target: certs/ca_cert.pem

volumes:
  log_volume:

networks:
  shared-network:
    external: true

secrets:
  ast_root_ca:
    file: ./certs/ca_cert.pem
