module.exports = {
    apps: [
        {
            name: 'webhook-handler',
            script: './dist/apps/webhooks/apps/webhooks/src/main.js',
            exec_mode: 'cluster',
            instances: 'max',
            max_memory_restart: '500M',
            env: {
                COMPONENT_TYPE: 'webhook',
                WEBHOOK_HANDLER_PORT: '3332',
                API_NODE_ENV: 'development',
            },
            env_homolog: {
                COMPONENT_TYPE: 'webhook',
                WEBHOOK_HANDLER_PORT: '3332',
                API_NODE_ENV: 'homolog',
            },
            env_production: {
                COMPONENT_TYPE: 'webhook',
                WEBHOOK_HANDLER_PORT: '3332',
                API_NODE_ENV: 'production',
            },
            autorestart: true,
            max_restarts: 10,
            min_uptime: '10s',
            kill_timeout: 5000,
        },
        {
            name: 'kodus-orchestrator',
            script: './dist/apps/api/apps/api/src/main.js',
            exec_mode: 'cluster',
            instances: 'max',
            max_memory_restart: '500M',
            env: {
                COMPONENT_TYPE: 'api',
                API_PORT: '3331',
                API_NODE_ENV: 'development',
            },
            env_homolog: {
                COMPONENT_TYPE: 'api',
                API_PORT: '3331',
                API_NODE_ENV: 'homolog',
            },
            env_production: {
                COMPONENT_TYPE: 'api',
                API_PORT: '3331',
                API_NODE_ENV: 'production',
            },
            autorestart: true,
            max_restarts: 10,
            min_uptime: '10s',
            kill_timeout: 5000,
        },
        {
            name: 'workflow-worker',
            script: './dist/apps/worker/apps/worker/src/main.js',
            exec_mode: 'cluster',
            instances: 'max',
            max_memory_restart: '500M',
            env: {
                COMPONENT_TYPE: 'worker',
                WORKFLOW_QUEUE_WORKER_ENABLED: 'true',
                API_NODE_ENV: 'development',
            },
            env_homolog: {
                COMPONENT_TYPE: 'worker',
                WORKFLOW_QUEUE_WORKER_ENABLED: 'true',
                API_NODE_ENV: 'homolog',
            },
            env_production: {
                COMPONENT_TYPE: 'worker',
                WORKFLOW_QUEUE_WORKER_ENABLED: 'true',
                API_NODE_ENV: 'production',
            },
            autorestart: true,
            max_restarts: 10,
            min_uptime: '10s',
            kill_timeout: 5000,
        },
    ],
};
