blank_issues_enabled: false
contact_links:
    - name: Questions / Discord
      url: https://discord.com/invite/TFZBRk9fT6
      about: Need help selfhosting or ask a general question about the project? Join our Discord server
