ARG API_CLOUD_MODE=false

FROM node:22.14.0-slim

ARG API_CLOUD_MODE
ENV API_CLOUD_MODE=${API_CLOUD_MODE}

WORKDIR /usr/src/app
ENV NODE_ENV=development
ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN corepack disable \
 && npm i -g yarn@1.22.22

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates python3 make g++ procps git \
    && rm -rf /var/lib/apt/lists/*

RUN npm i -g yalc chokidar-cli nodemon

COPY package.json yarn.lock ./
COPY nest-cli.json tsconfig*.json ./
RUN mkdir -p /usr/src/app/certs

CMD ["sh", "-c", "yarn install --frozen-lockfile && yarn start:dev:worker"]
