export interface OutboxMessage {
    /**
     * Optional explicit UUID for the outbox message.
     * Note: outbox row UUID is generated by the database/ORM (PrimaryGeneratedColumn).
     */
    uuid?: string;
    jobId: string;
    exchange: string;
    routingKey: string;
    payload: Record<string, unknown>;
}
