export enum WorkflowType {
    CODE_REVIEW = 'CODE_REVIEW',
    CRON_CHECK_PR_APPROVAL = 'CRON_CHECK_PR_APPROVAL',
    CRON_KODY_LEARNING = 'CRON_KODY_LEARNING',
    CRON_CODE_REVIEW_FEEDBACK = 'CRON_CODE_REVIEW_FEEDBACK',
}
